# Generated by Django 2.2.7 on 2019-11-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_afeccion', models.TextField(blank=True, null=True)),
                ('causa_afeccion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cultivo', models.TextField(blank=True, null=True)),
                ('guia_cultivo', models.TextField(blank=True, null=True)),
                ('imagen_cultivo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_diagnostico', models.DateTimeField()),
                ('hora_diagnostico', models.DateField()),
                ('longitud_diagnostico', models.FloatField()),
                ('latitud_diagnostico', models.FloatField()),
                ('afeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Afeccion')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tratamiento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField(blank=True, null=True)),
                ('correo_usuario', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_usuario', models.TextField(blank=True, null=True)),
                ('contrasenia_usuario', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Cultivo')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Diagnostico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoAfeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Afeccion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Prevencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('afeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Afeccion')),
            ],
        ),
        migrations.CreateModel(
            name='CultivoAfeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Afeccion')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Cultivo')),
            ],
        ),
    ]
