# Generated by Django 2.2.7 on 2019-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocultivo',
            name='imagen_usuarioCultivo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
