# Generated by Django 2.2.7 on 2019-11-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0002_usuariocultivo_imagen_usuariocultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocultivo',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plantas.Diagnostico'),
        ),
    ]
