# Generated by Django 2.2.7 on 2019-12-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0003_auto_20191123_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariocultivo',
            old_name='cultivo',
            new_name='Cultivo',
        ),
        migrations.RenameField(
            model_name='usuariocultivo',
            old_name='diagnostico',
            new_name='Diagnostico',
        ),
        migrations.RenameField(
            model_name='usuariocultivo',
            old_name='usuario',
            new_name='Usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
