# Generated by Django 2.2.7 on 2019-12-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0004_auto_20191212_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen_usuario',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
