# Generated by Django 2.2.7 on 2019-12-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0005_auto_20191212_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='fecha_diagnostico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='hora_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='latitud_diagnostico',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='longitud_diagnostico',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
